%define		_modname	parsekit
%define		_status		alpha

Summary:	%{_modname} - PHP Opcode Analyser
Summary(pl):	%{_modname} - Analizator instrukcji PHP
Name:		php-pecl-%{_modname}
Version:	1.0
Release:	1
License:	PHP
Group:		Development/Languages/PHP
Source0:	http://pecl.php.net/get/%{_modname}-%{version}.tgz
# Source0-md5:	9a219eec9c4b9b10cbd06570f83fc52c
URL:		http://pecl.php.net/package/parsekit/
BuildRequires:	php-devel
Requires:	php-common
Obsoletes:	php-pear-%{_modname}
BuildRoot:	%{tmpdir}/%{name}-%{version}-root-%(id -u -n)

%define		_sysconfdir	/etc/php
%define		extensionsdir	%{_libdir}/php

%description
Provides a userspace interpretation of the opcodes generated by the
Zend engine compiler built into PHP.

This extension is meant for development and debug purposes only and
contains some code which is potentially non-threadsafe.

In PECL status of this extension is: %{_status}.

%description -l pl
Dostarcza dzia³aj±cego w przestrzeni u¿ytkownika interpretera
instrukcji wygenerowanych przez kompilator silnika Zend wbudowany w
PHP.

To rozszerzenie przeznaczone jest do rozwoju oraz w celu wyszukiwania
b³êdów. Zawiera kod, który potencjalnie nie jest bezpieczny dla
aplikacji wielow±tkowych.

To rozszerzenie ma w PECL status: %{_status}.

%prep
%setup -q -c

%build
cd %{_modname}-%{version}
phpize
%configure
%{__make}

%install
rm -rf $RPM_BUILD_ROOT
install -d $RPM_BUILD_ROOT%{extensionsdir}

install %{_modname}-%{version}/modules/%{_modname}.so $RPM_BUILD_ROOT%{extensionsdir}

%clean
rm -rf $RPM_BUILD_ROOT

%post
%{_sbindir}/php-module-install install %{_modname} %{_sysconfdir}/php-cgi.ini

%preun
if [ "$1" = "0" ]; then
	%{_sbindir}/php-module-install remove %{_modname} %{_sysconfdir}/php-cgi.ini
fi

%files
%defattr(644,root,root,755)
%doc %{_modname}-%{version}/README
%attr(755,root,root) %{extensionsdir}/%{_modname}.so
