%define		php_name	php%{?php_suffix}
%define		modname	parsekit
%define		status		stable
Summary:	%{modname} - PHP Opcode Analyser
Summary(pl.UTF-8):	%{modname} - Analizator instrukcji PHP
Name:		%{php_name}-pecl-%{modname}
Version:	1.3.0
Release:	8
License:	PHP
Group:		Development/Languages/PHP
Source0:	http://pecl.php.net/get/%{modname}-%{version}.tgz
# Source0-md5:	6045927d06da9f5b8852d220142018bc
URL:		http://pecl.php.net/package/parsekit/
BuildRequires:	%{php_name}-devel >= 3:5.0.4
BuildRequires:	rpmbuild(macros) >= 1.650
%{?requires_php_extension}
Provides:	php(%{modname}) = %{version}
Obsoletes:	php-pecl-parsekit < 1.3.0-7
BuildRoot:	%{tmpdir}/%{name}-%{version}-root-%(id -u -n)

%description
Provides a userspace interpretation of the opcodes generated by the
Zend engine compiler built into PHP.

This extension is meant for development and debug purposes only and
contains some code which is potentially non-threadsafe.

In PECL status of this extension is: %{status}.

%description -l pl.UTF-8
Dostarcza działającego w przestrzeni użytkownika interpretera
instrukcji wygenerowanych przez kompilator silnika Zend wbudowany w
PHP.

To rozszerzenie przeznaczone jest do rozwoju oraz w celu wyszukiwania
błędów. Zawiera kod, który potencjalnie nie jest bezpieczny dla
aplikacji wielowątkowych.

To rozszerzenie ma w PECL status: %{status}.

%prep
%setup -qc
mv %{modname}-%{version}/* .

%build
phpize
%configure
%{__make}

%install
rm -rf $RPM_BUILD_ROOT
install -d $RPM_BUILD_ROOT{%{php_sysconfdir}/conf.d,%{php_extensiondir}}
install -p modules/%{modname}.so $RPM_BUILD_ROOT%{php_extensiondir}
cat <<'EOF' > $RPM_BUILD_ROOT%{php_sysconfdir}/conf.d/%{modname}.ini
; Enable %{modname} extension module
extension=%{modname}.so
EOF

%clean
rm -rf $RPM_BUILD_ROOT

%post
%php_webserver_restart

%postun
if [ "$1" = 0 ]; then
	%php_webserver_restart
fi

%files
%defattr(644,root,root,755)
%doc README
%config(noreplace) %verify(not md5 mtime size) %{php_sysconfdir}/conf.d/%{modname}.ini
%attr(755,root,root) %{php_extensiondir}/%{modname}.so
